"""Criar tabela movimentacao

Revision ID: 25766c64dae8
Revises: ea1a01700e55
Create Date: 2026-06-01 11:06:36.156168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25766c64dae8'
down_revision: Union[str, Sequence[str], None] = 'ea1a01700e55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('imagem_path', sa.String(length=255), nullable=True))
    op.drop_column('produtos', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('image_path', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('produtos', 'imagem_path')
    # ### end Alembic commands ###
